spring.application.name=pos

server.port=8080

# database connection
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/java_pos_db
spring.datasource.name=java_pos_db
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# app settings
logging.level.root=warn
spring.main.banner-mode=off